### ISSUE TITLE
Session gets destroy sometime

### ISSUE THREAD

**Issue by praveend06** [ezimuel/PHP-Secure-Session#18]
I am using this library to secure session. Sometime users session gets destroy.
Trouble  shooting her to find out the reason.

How this PHP_Secure_Session library works.
What is purpose of KEY_.. name?

**Comment by ezimuel** [comment]
Do you have any evidence on the issue? Maybe some log file? 
The KEY_ is a cookie that contains the encryption and authentication keys.
I'm planning to rewrite this class from scratch, it's an old project and I don't want people to continue to use it in 2016!

**Comment by sarangpahurkar** [comment]
On subsequent request new session id gets created and this behavior is not for all incoming request. Only sometime it creates new session id itself.

**Comment by ezimuel** [comment]
@praveend06 according to your settings:
```
session.gc_maxlifetime = 1440
session.gc_probability = 1
session.gc_divisor = 1000
session.cookie_lifetime = 0
```
The lifetime of the session will expire only when the user will close the browser (`cookie_lifetime = 0`) but, because you have also the *garbage collection* (gc) settings in place, for every session initialization the gc will be executed with a probability of 1/1000 (`gc_probability / gc_divisor`). If the gc is executed it will destroy all the files not updated in the last 24 min (1440 sec).

You can check if the issue is related to your gc settings putting `gc_probaility = 0`, that means never execute the *garbage collection*. If this is the case, you can adjust the gc settings according to your needs, maybe increase the `gc_maxlifetime` and the `gc_divisor` parameters.

**Comment by SvenRtbg** [comment]
@ezimuel If you feel that your code does not live up to your own expectations, it is a fair move to withdraw it from public consumption.

**Comment by ezimuel** [comment]
@SvenRtbg all the source code may contain issue, I'm working to fix it after your report in #19. I don't think I need to stop to release it, I can just put a warning in the README. The issue #19 even if possible it's quite rare and it's not so critical, we are talking about session data.

**Comment by ezimuel** [comment]
@praveend06, @sarangpahurkar I rewrote from scratch the Session Handler, you can test it the new implementation. It should fix all the previous issues. Now the implementation supports composer, please read the [README.md](https://github.com/ezimuel/PHP-Secure-Session/blob/master/README.md) for information.

**Comment by praveend06** [comment]
@ezimuel, just want to confirm are you suggesting to use [https://github.com/ezimuel/PHP-Secure-Session/blob/master/README.md](url) instead of old.  My server is running php5.3 version. I hope new library will work on this version?

**Comment by ezimuel** [comment]
@praveend06 I'm sorry but this new version requires at least PHP 5.5. Please note that PHP 5.3 and PHP 5.4 are no longer supported since 2014 and 2015, this means if you are using it for a production environment you are exposing your application to potential security issues. I strongly suggest to upgrade it at PHP 5.6, because the end of life of PHP 5.5 will be 10 July 2016.

**Comment by ezimuel** [comment]
@praveend06 regarding the vendor/autoload.php, it will be auto-generated by composer when you require the php-secure-session project. If you want to install it manually, you need to use the following command:
```
composer install
```
Read the [composer documentation](https://getcomposer.org/doc/00-intro.md) for more information.
