### ISSUE TITLE
Session wrapper loses data when serving concurrent requests.

### ISSUE THREAD

**Issue by SvenRtbg** [ezimuel/PHP-Secure-Session#19]
The default PHP session handler aquires a lock before reading data, and releases this lock after data has been written back. This class doesn't do anything like this, so concurrent requests (two or more) will be able to all read the data, all modify them in different places, and then write them back one after the other - and the request writing last overwrites any changes from previous writes.

**Comment by ezimuel** [comment]
@SvenRtbg due to the nature of session data concurrent requests will refer to different files (different sessions). So, in the theory, there should not be possible to overwrite the same file.
That said, you are right that this [file_put_contents() usage](https://github.com/ezimuel/PHP-Secure-Session/blob/master/SecureSession.php#L183) can be dangerous. I'll add the LOCK_EX options here.
Anyway, I'm considering to rewrite this project from scratch because I wrote it many years ago as an experiment but it seems that people continue to use it.
Thanks for your feedback!

**Comment by praveend06** [comment]
We have added a lock when write session in file
$bytes      = file_put_contents($sessFile, $encrypted['hmac'] . ':' . base64_encode($encrypted['iv']) . ':' . base64_encode($encrypted['encrypted']), LOCK_EX);

But even we observed that some time session gets destroyed.
Unable to troubleshoot why session gets destroyed. Please guide to troubleshoot how session got destroyed.

**Comment by ezimuel** [comment]
@praveend06 the LOCK_EX doesn't prevent the destroy of session. I think your issue is more related to the lifetime of session used by the garbage collection of PHP. Which php.ini values are you using for `session.gc_maxlifetime`, `session.gc_probability` and `session.gc_divisor`?

**Comment by praveend06** [comment]
Following is my php.ini setting, please suggest if any changes is require in this.

session.gc_maxlifetime = 1440
session.gc_probability = 1
session.gc_divisor = 100

**Comment by ezimuel** [comment]
@praveend06 session.cookie_lifetime is equal to 0?

**Comment by praveend06** [comment]
Yes , its all ready set to o.
 session.cookie_lifetime	0

**Comment by ezimuel** [comment]
@praveend06 continue the discussion in #18.

**Comment by SvenRtbg** [comment]
@ezimuel I don't think you understand the problem correctly. 

What is currently missing is that when calling `open()` or `read()`, your class has to aquire an exclusive file lock onto the stored session file, and keep it. It must only be released after `write()` has written the data back, or when `close()` is supposed to close the resource.

Hence you cannot use `file_get_contents()` because this function does not allow you to aquire a file lock and keep it. In the same way using `file_put_contents()` is flawed because all you can do is to avoid concurrent writes to the same file by using `LOCK_EX`, but this does not use the file lock that must have been aquired when reading the file.

**Comment by SvenRtbg** [comment]
As a pointer to a better implementation, I'd suggest extending http://php.net/manual/en/class.sessionhandler.php - as it is written in the documentation, you'd be able to add crypto to `read()` and `write()` without the need to deal with all other details. This will also open this solution to work with other session save handlers besides `files`, like `memcached` etc.

**Comment by ezimuel** [comment]
@SvenRtbg I underestimated the issue, you are right. Even if multiple requests will come from different SESSION_ID we can have ajax calls from the same browser and potentially fall in a race condition (especially with high traffic website). The LOCK_EX on the file_put_contents() is not enough because we have the file_get_contents() that is not checking for file lock. I'll work on a fix to put lock on the read() and unlock when write() is finished or, even better, I will bypass the issue extending the SessionHandler of PHP, providing only encrypt and decrypt of data.
Thanks for the report, I'm re-opening the issue.

**Comment by ezimuel** [comment]
@SvenRtbg I re-implemented from scratch the Secure Session Handler using the idea of extending the SessionHandler of PHP. This new implementation fixes the #19 issue and give use more flexibility, see the [README](https://github.com/ezimuel/PHP-Secure-Session/blob/master/README.md) for more details.
