### ISSUE TITLE
Error in session_start

### ISSUE THREAD

**Issue by Gm3z** [ezimuel/PHP-Secure-Session#33]
Hello @ezimuel 

I am using your library. I followed all of the steps in the README.md but I have some problems and I don't know what is the problem, Can you help me about this?

`PHP Warning:  session_start(): Failed to decode session object. Session has been destroyed`

```
NOTICE: PHP message: PHP Fatal error:  Uncaught PHPSecureSession\Exception\AuthenticationFailedException: Authentication failed in /var/www/html/vendor/ezimuel/php-secure-session/src/SecureHandler.php:125
Stack trace:
#0 /var/www/html/vendor/ezimuel/php-secure-session/src/SecureHandler.php(63): PHPSecureSession\SecureHandler->decrypt('tiempo_sesion|i...', 'gv\x9C\xAA\xBF\xE6\r|\xB3\xF9VG\xDE\x8B ...')
#1 [internal function]: PHPSecureSession\SecureHandler->read('jaOogRV2lSyUpl1...')
#2 /var/www/html/Core/index.php(15): session_start()
#3 {main}
  thrown in /var/www/html/vendor/ezimuel/php-secure-session/src/SecureHandler.php on line 125
```
Thank you so much!

**Comment by ezimuel** [comment]
@Gm3z I found error ` session_start(): Failed to decode session object. Session has been destroyed` mentioned [here](https://stackoverflow.com/questions/55070634/session-start-failed-to-decode-session-object) on stackoverflow. 
Are you using file to store the session data? If you changed the `session.save_path` this must be an absolute path. Moreover, the path that you specify must have read and write permissions by PHP.

**Comment by Gm3z** [comment]
Hello @ezimuel 

Yes, I store the session data in a file also I changed the path in the php.ini file, this value is session.save_path = "/var/www/sessions"

I read the link that you posted and I try to solve the problem.

**Comment by ezimuel** [comment]
I do not recommend to store the session data in `/var/www` since this folder is usually exposed by webserver such as Apache or nginx. I suggest to use a different folder. Moreover, be sure that PHP has privileges to write and read on this folder. For instance, PHP runs with user `www-data`on GNU/Linux using nginx.

**Comment by Gm3z** [comment]
I checked the permissions and they're correct. Thank you for your suggestion but I can't change the folder because I have a restriction with open_base_dir. Sometimes the KEY value in the cookie dissapear.

**Comment by ezimuel** [comment]
OK, just another check can you try to specify the folder `session.save_path = "/tmp"`? The `/tmp` folder is a special folder in Linux that everyone can use it. It's just a test since it's not recommended for security reason to use it. If this works fine means it's a problem of the folder `/var/www/sessions`.

**Comment by Gm3z** [comment]
Thank for the information. If I have another question, I will open a new issue.
